meta:
  enable_passive_url_detection: true
  enable_commands: true
  censor_trackers: true
  debug: true

whitelist:
  - youtube.com
  - youtu.be
  - twitter.com
  - x.com
  - rumble.com
  - odysee.com
  - bitchute.com
  - 4cdn.org
  - tenor.com

ytdlp:
  active_preset: "Default Preset"
  presets:
    - name: "Default Preset"
      format: "bestvideo[height<=720]+bestaudio/best[height<=720]"
      fallback_formats:
        - "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
        - "worst"

ffmpeg:
  enable_livestream_previews: True
  livestream_args:
    - "-c"
    - "copy"
    - "-bsf:a"
    - "aac_adtstoasc"
    - "-movflags"
    - "+frag_keyframe+empty_moov"
    - "-t"
    - "90"
    - "-f"
    - "mp4"
  enable_thumbnail_generation: true
  thumbnail_args: false # not yet implemented

file:
  output_path: "-" # stream to memory
  max_duration: 1200 # seconds
  max_in_memory_file_size: 104857600 # bytes
  max_file_size: 104857600 # bytes
  max_retries: 1 # Not yet implemented
  async_upload: false # Experimental

queue:
  max_size: 12
  max_message_url_count: 1

log: # wip
  debug: true
  exception: true
  warning: true
  info: true

command:
  query_image:
    tenor_api_key:
    unsplash_api_key:
