meta:
  enable_passive_url_detection: true
  enable_commands: true
  censor_trackers: true
  debug: true

whitelist:
  - youtube.com
  - youtu.be
  - twitter.com
  - x.com
  - rumble.com
  - odysee.com
  - bitchute.com
  - 4cdn.org
  - tenor.com
  - unsplash.com
  - waifu.im

ytdlp:
  active_preset: "Default Preset"
  presets:
    - name: "Default Preset"
      format: "worst"
      fallback_formats:
        - "bestvideo[height<=720]+bestaudio/best[height<=720]"
        - "bestvideo[height<=1080]+bestaudio/best[height<=1080]"

ffmpeg:
  enable_livestream_previews: True
  livestream_args: false # not yet implemented
  enable_thumbnail_generation: true
  thumbnail_args: false # not yet implemented

file:
  max_duration: 1200 # seconds
  max_in_memory_file_size: 104857600 # bytes
  max_file_size: 104857600 # bytes

queue:
  preprocessor_worker_limit: 10
  # [Preprocess Worker]
  # Role: Dynamically instantiated asyncio tasks that handle event preprocessing.
  # Trigger: Activated when validated events arrive from the main event loop.
  # Purpose: Add the initial hourglass reaction and enqueue the preprocessed event.

  event_queue_capacity: 100
  # [Preprocessed Event Queue]
  # Role: Static asyncio queue buffer for validated, preprocessed events.
  # Trigger: Instantiated in the plugin start method.
  # Purpose: Prevents overload by buffering events when downstream processing lags behind event arrival.

  processor_worker_count: 1
  # [Process Worker]
  # Role: Static asyncio tasks handle event processing.
  # Trigger: Instantiated in the plugin start method.
  # Purpose: Continuously dequeues, processes, and renders media.

  max_message_url_count: 1 # If a message has >= this amount of urls it is not processed.

log: # wip
  debug: true
  exception: true
  warning: true
  info: true

command:
  command_prefix: "!"
  query_image:
    tenor_api_key:
    unsplash_api_key:
