meta:
  enable_passive_url_detection: true
  enable_commands: true
  censor_trackers: true
  use_platform_domains_as_whitelist: true # Does not apply to query commands
  debug: false

file:
  max_duration: 1200 # seconds
  max_audio_only_duration: 7560 # seconds
  max_in_memory_file_size: 104857600 # bytes
  max_file_size: 104857600 # bytes

queue:
  preprocess_worker_limit: 10
  event_queue_capacity: 100
  process_worker_count: 1
  max_message_url_count: 1

command:
  command_prefix: "!"
  query_image:
    tenor_api_key: "SECRET"
    giphy_api_key: "SECRET"
    unsplash_api_key: "SECRET"
    searx_instance: "https://<your-searx-instance>/search"

ytdlp:
  enable_thumbnail_fallback_if_duration_or_size_exceeds: true

ffmpeg:
  enable_livestream_previews: true
  livestream_preview_length: 15 # seconds
  enable_thumbnail_generation: true
  enable_video_postprocessing: true
  video_input_args:
    - "-nostdin"
  video_output_args:
    - "-f"
    - "mp4" # Set output format to MP4
    - "-c:v"
    - "libx264" # Use H.264 codec for video
    - "-preset"
    - "fast" # Set the encoding preset to 'fast'
    - "-c:a"
    - "aac" # Use AAC codec for audio
    - "-b:a"
    - "192k" # Set audio bitrate to 192 kbps
    - "-movflags"
    - "+faststart" # Optimize for web streaming
  video_output_ext: "mp4"
  enable_audio_postprocessing: true # Only applies to audio not downloaded using yt-dlp, it already is converted to mp3
  audio_input_args:
    - "-nostdin"
  audio_output_args:
    - "-f"
    - "mp3" # Set output format to MP3
    - "-c:a"
    - "libmp3lame" # Use LAME codec for MP3 audio
    - "-b:a"
    - "192k" # Set audio bitrate to 192 kbps
  audio_output_ext: "mp3"

platforms:
  - domain: "youtube.com"
    config_key: "youtube"
  - domain: "youtu.be"
    config_key: "youtube"
  - domain: "twitter.com"
    config_key: "x"
  - domain: "x.com"
    config_key: "x"
  - domain: "rumble.com"
    config_key: "generic1"
  - domain: "odysee.com"
    config_key: "generic1"
  - domain: "bitchute.com"
    config_key: "generic1"
  - domain: "catbox.moe"
    config_key: "generic2"
  - domain: "4cdn.org"
    config_key: "generic2"

platform_configs:
  # Note: yt-dlp formats do not apply if audio-only command is used.
  youtube:
    name: "youtube"
    enable_cookies: false
    enable_proxy: false
    proxy: "SECRET"
    enable_custom_user_agent: false
    custom_user_agent: "PLACEHOLDER"
    ytdlp: true
    ytdlp_formats:
      - "bestvideo[height<=720]+bestaudio/best[height<=720]"
      - "worst"
    cookies_file: |

  x:
    name: "x"
    enable_cookies: false
    enable_proxy: false
    proxy: "SECRET"
    enable_custom_user_agent: false
    custom_user_agent: "PLACEHOLDER"
    ytdlp: true
    ytdlp_formats:
      - "bestvideo[height<=720]+bestaudio/best[height<=720]"
      - "worst"
    cookies_file: |

  generic1:
    name: "generic1"
    enable_cookies: false
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    ytdlp: true
    ytdlp_formats:
      - "worst"
    cookies_file: |

  generic2:
    name: "generic2"
    enable_cookies: false
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    ytdlp: false

  query:
    name: "query"
    enable_cookies: false
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    ytdlp: false
