meta:
  enable_passive_url_detection: true
  enable_commands: true
  censor_trackers: true
  debug: false
  enable_proxy: false # only implemented for yt-dlp right now
  proxy: "SECRET"
  enable_custom_user_agent: False # only implemented for yt-dlp right now
  custom_user_agent: "PLACEHOLDER"

whitelist:
  - "youtube.com"
  - "youtu.be"
  - "twitter.com"
  - "x.com"
  - "rumble.com"
  - "odysee.com"
  - "bitchute.com"
  - "4cdn.org"
  - "tenor.com"
  - "unsplash.com"
  - "waifu.im"

ffmpeg:
  enable_livestream_previews: true
  livestream_preview_length: 15 # seconds
  enable_thumbnail_generation: true

file:
  max_duration: 1200 # seconds
  max_in_memory_file_size: 104857600 # bytes
  max_file_size: 104857600 # bytes
  enable_normalize_videos_to_mp4: true
  enable_normalize_audio_to_mp3: true

queue:
  preprocess_worker_limit: 10
  event_queue_capacity: 100
  process_worker_count: 1
  max_message_url_count: 1

command:
  command_prefix: "!"
  query_image:
    tenor_api_key: "SECRET"
    unsplash_api_key: "SECRET"

ytdlp:
  enable_thumbnail_fallback_if_duration_or_size_exceeds: true
  active_preset: "Default"
  presets:
    - name: "Default"
      formats:
        - "worst"
        - "bestvideo[height<=720]+bestaudio/best[height<=720]"
        - "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
  enable_cookies: False

  # In maubout manager paste the cookies in underneath cookies file. Make sure the line stays intact. Then highlight the text and press tab or shift-tab until the text is red.
  cookies_file: |
