meta:
  enable_passive_url_detection: true
  enable_commands: true
  censor_trackers: true
  use_platform_domains_as_whitelist: true
  debug: false

file:
  max_duration: 1200 # seconds
  max_in_memory_file_size: 104857600 # bytes
  max_file_size: 104857600 # bytes

queue:
  preprocess_worker_limit: 10
  event_queue_capacity: 100
  process_worker_count: 1
  max_message_url_count: 1

command:
  command_prefix: "!"
  query_image:
    tenor_api_key: "SECRET"
    unsplash_api_key: "SECRET"

ytdlp:
  enable_thumbnail_fallback_if_duration_or_size_exceeds: true

ffmpeg:
  enable_livestream_previews: true
  livestream_preview_length: 15 # seconds
  enable_thumbnail_generation: true
  enable_normalize_videos_to_mp4: true
  enable_normalize_audio_to_mp3: true

platforms:
  - domain: "youtube.com"
    config_key: "youtube"
  - domain: "youtu.be"
    config_key: "youtube"
  - domain: "twitter.com"
    config_key: "x"
  - domain: "x.com"
    config_key: "x"
  - domain: "rumble.com"
    config_key: "generic1"
  - domain: "odysee.com"
    config_key: "generic1"
  - domain: "bitchute.com"
    config_key: "generic1"
  - domain: "4cdn.org"
    config_key: "generic2"
  - domain: "tenor.com"
    config_key: "generic2"
  - domain: "unsplash.com"
    config_key: "generic2"
  - domain: "waifu.im"
    config_key: "generic2"
  - domain: "workers.dev"
    config_key: "generic2"

platform_configs:
  youtube:
    enable_cookies: true
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    force_ytdlp: true
    ytdlp_formats:
      - "bestvideo[height<=720]+bestaudio/best[height<=720]"
      - "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
      - "worst"
    cookies_file: |

  x:
    enable_cookies: true
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    force_ytdlp: true
    ytdlp_formats:
      - "bestvideo[height<=720]+bestaudio/best[height<=720]"
      - "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
      - "worst"
    cookies_file: |

  generic1:
    enable_cookies: false
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    force_ytdlp: true
    ytdlp_formats:
      - "worst"
    cookies_file: |

  generic2:
    enable_cookies: false
    enable_proxy: true
    proxy: "SECRET"
    enable_custom_user_agent: true
    custom_user_agent: "PLACEHOLDER"
    force_ytdlp: false
    ytdlp_formats:
      - "worst"
    cookies_file: |
